import type { ProductCard } from "@/components/product/productData"

export const collectionProducts: ProductCard[] = [
  {
    id: "eyewear-heritage-1",
    name: "Heritage Oval",
    price: "₹8,999",
    category: "Heritage",
    type: "Sunglasses",
    shape: "oval",
    material: "acetate",
    colorGroup: "monochrome",
    image: "/images/products/product1.png",
    alt: "Classic Heritage Oval sunglasses in glossy black frame",
    badge: "BESTSELLER",
    swatches: ["#000000", "#6f5639", "#ebe8e1"],
    gallery: ["/images/products/product1.png", "/images/products/product5.png", "/images/products/product9.png"],
  },
  {
    id: "eyewear-heritage-2",
    name: "Heritage Aviator",
    price: "₹9,500",
    category: "Heritage",
    type: "Sunglasses",
    shape: "aviator",
    material: "titanium",
    colorGroup: "blue",
    image: "/images/products/product2.png",
    alt: "Heritage Aviator sunglasses with dark metal frame",
    swatches: ["#5b82ab", "#111722"],
    gallery: ["/images/products/product2.png", "/images/products/product6.png", "/images/products/product10.png"],
  },
  {
    id: "eyewear-noyer-1",
    name: "Noyer Square",
    price: "₹10,500",
    category: "Noyer",
    type: "Optical",
    shape: "square",
    material: "acetate",
    colorGroup: "crystal",
    image: "/images/products/product3.png",
    alt: "Noyer Square clear acetate optical frames",
    badge: "NEW LAUNCH",
    swatches: ["#ebe8e1", "#6f5639"],
    gallery: ["/images/products/product3.png", "/images/products/product7.png", "/images/products/product11.png"],
  },
  {
    id: "eyewear-noyer-2",
    name: "Noyer D-Frame",
    price: "₹11,000",
    category: "Noyer",
    type: "Sunglasses",
    shape: "d-frame",
    material: "acetate",
    colorGroup: "tortoiseshell",
    image: "/images/products/product4.png",
    alt: "Noyer D-Frame acetate sunglasses in tortoiseshell",
    swatches: ["#6f5639", "#000000"],
    gallery: ["/images/products/product4.png", "/images/products/product8.png", "/images/products/product12.png"],
  },
  {
    id: "eyewear-crystal-1",
    name: "Crystal Round",
    price: "₹9,200",
    category: "Crystal",
    type: "Optical",
    shape: "round",
    material: "clear crystal",
    colorGroup: "crystal",
    image: "/images/products/product5.png",
    alt: "Crystal Round transparent acetate optical frames",
    swatches: ["#ebe8e1", "#5b82ab"],
    gallery: ["/images/products/product5.png", "/images/products/product9.png", "/images/products/product13.png"],
  },
  {
    id: "eyewear-crystal-2",
    name: "Crystal Cateye",
    price: "₹9,800",
    category: "Crystal",
    type: "Sunglasses",
    shape: "cat-eye",
    material: "clear crystal",
    colorGroup: "gold",
    image: "/images/products/product6.png",
    alt: "Crystal Cateye sunglasses in clear mist hue",
    swatches: ["#ebe8e1", "#111722"],
    gallery: ["/images/products/product6.png", "/images/products/product10.png", "/images/products/product14.png"],
  },
  {
    id: "eyewear-atelier-1",
    name: "Atelier Hexagon",
    price: "₹12,500",
    category: "Atelier",
    type: "Sunglasses",
    shape: "hexagon",
    material: "titanium",
    colorGroup: "monochrome",
    image: "/images/products/product7.png",
    alt: "Atelier Hexagon premium metal sunglasses",
    badge: "LIMITED EDITION",
    swatches: ["#111722", "#6f5639"],
    gallery: ["/images/products/product7.png", "/images/products/product11.png", "/images/products/product15.png"],
  },
  {
    id: "eyewear-atelier-2",
    name: "Atelier Panto",
    price: "₹13,000",
    category: "Atelier",
    type: "Optical",
    shape: "round",
    material: "titanium",
    colorGroup: "monochrome",
    image: "/images/products/product8.png",
    alt: "Atelier Panto premium titanium optical frames",
    swatches: ["#000000", "#ebe8e1"],
    gallery: ["/images/products/product8.png", "/images/products/product12.png", "/images/products/product1.png"],
  },
  {
    id: "eyewear-edits-1",
    name: "The Havane",
    price: "₹16,500",
    category: "Edits",
    type: "Sunglasses",
    shape: "oval",
    material: "acetate",
    colorGroup: "tortoiseshell",
    image: "/images/products/product1.png",
    alt: "The Havane curated editorial eyewear",
    badge: "CURATED EDIT",
    swatches: ["#6f5639", "#000000"],
    gallery: ["/images/products/product1.png", "/images/products/product5.png", "/images/products/product9.png"],
  },
  {
    id: "eyewear-edits-2",
    name: "The Aube",
    price: "₹15,900",
    category: "Edits",
    type: "Sunglasses",
    shape: "square",
    material: "titanium",
    colorGroup: "gold",
    image: "/images/products/product2.png",
    alt: "The Aube curated editorial eyewear",
    badge: "LIMITED RELEASE",
    swatches: ["#111722", "#ebe8e1"],
    gallery: ["/images/products/product2.png", "/images/products/product6.png", "/images/products/product10.png"],
  },
  {
    id: "eyewear-edits-3",
    name: "The Lumen",
    price: "₹18,500",
    category: "Edits",
    type: "Sunglasses",
    shape: "d-frame",
    material: "titanium",
    colorGroup: "monochrome",
    image: "/images/products/product7.png",
    alt: "The Lumen curated editorial eyewear",
    badge: "EXCLUSIVE",
    swatches: ["#000000", "#6f5639"],
    gallery: ["/images/products/product7.png", "/images/products/product11.png", "/images/products/product15.png"],
  },
  {
    id: "eyewear-edits-4",
    name: "The Brume",
    price: "₹15,900",
    category: "Edits",
    type: "Sunglasses",
    shape: "round",
    material: "acetate",
    colorGroup: "monochrome",
    image: "/images/products/product4.png",
    alt: "The Brume curated editorial eyewear",
    badge: "EDITORIAL FAVOURITE",
    swatches: ["#000000", "#ebe8e1"],
    gallery: ["/images/products/product4.png", "/images/products/product8.png", "/images/products/product12.png"],
  },
]
